#!/usr/bin/env bash

read -p "wvlist password - " -s WVLISTPASS
echo

while [[ 1 == 1 ]]
do
    read -p "Command - " WVLISTCOMM
    
    if [[ "$WVLISTCOMM" == "quit" || "$WVLISTCOMM" == "exit" ]]
    then
        exit 0

    elif [[ "$WVLISTCOMM" != "" ]]
    then
        curl --user "$WVLISTUNAME:$WVLISTPASS" -G "${WVLISTHOST/%\/}/api/v1/admin" --data-urlencode "command=$WVLISTCOMM"
    fi
done
